apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: u31yvyhk6-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:e9feffade7fe90275a437bf23d6bf8433ec0903a@sha256:79ea86c4b0d2067cbefb9bc4346c1eae36da2ff6d8588a6b52108910e8544526
          name: container-image
